config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :posts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

    root "main#index"
    get "likes/check_like/:id", to: "likes#check_like", as: "like_post"
    get "likes/check_dislike/:id", to: "likes#check_dislike", as: "dislike_post"
    get "friends/:post_user_id", to: "friends#friendly", as: "friendly_post"
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user #у одного комментария один user
    belongs_to :post #у одного комментария свой пост
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authorize_user, except: [:index, :show]

  # GET /comments or /comments.json
  def index
    pp(11111111111111)
    @comments = Comment.where(post_id: params[:post_id])
   end

  helper_method :back

  def back
    pp(22222222222222222)
    request.referer
  end

  # GET /comments/1 or /comments/1.json
  def show
    pp(33333333333333333333333)
  end

  # GET /comments/new
  def new
    pp(4444444444444444444444)
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    pp(55555555555555555555555)
    @comment = Comment.find_by(user_id: current_user.id, id: (params[:id]))
    if @comment.nil?
        pp(666666666666666666666666)
        redirect_to root_path
    else
        pp(777777777777777777777777)
    end
  end

  # POST /comments or /comments.json
  def create
    pp(888888888888888888888)
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]

    respond_to do |format|
      if @comment.save
        pp(99999999999999999999999)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        pp(101010101010010101010)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    pp(1212121212121212121)
    @comments = Comment.where(post_id: params[:post_id])
    respond_to do |format|
      if @comment.update(comment_params)
        pp(1313131313131313)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        pp(141414141414141414141414)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    pp(1515151515151515)
    @comment.destroy

    respond_to do |format|
        pp(191919191919)
      format.html { redirect_to comments_url(post_id: @comment.post_id), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    def authorize_user
        pp(1616161616161616161616)
        if current_user
            pp(17171717171717171717)
        return true
        else
            pp(1818181818181818)
        redirect_to root_path, alert: "You are not authorized to edit this post."
        end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
        pp(20202020202020)
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
        pp(21212121212121)
      params.require(:comment).permit(:message, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Message <%= comment.user.first_name%> <%= comment.user.last_name%>:</strong>
    <%= comment.message %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
    <% if comment.errors.any? %>
    <div style="color: red">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

     <div>
        <%= form.label :message, style: "display: block" %>
        <%= form.text_area :message %>
     </div>

    <%= hidden_field_tag :post_id, params[:post_id] %>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> 
</div>

app/views/comments/index.html.erb
<% if user_signed_in? %>

    <p style="color: green"><%= notice %></p>

    <h1>Comments</h1>
    <p>
        <%= link_to "New comment", new_comment_path(post_id: params[:post_id] ) %>
        <%= link_to "Back to main", root_path %>
    </p>
    <div id="comments">
        <% @comments.each do |comment| %>
            <%= render comment %>
                <% if comment.user == current_user %>
                    <p>
                    <%= link_to "Show this comment", comment %>
                    </p>
                <% end %>
        <% end %>
    </div>


<% else %>
  <h1>Home</h1>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
 
  <%= link_to "Back", back %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @comment %>
<div>
    <% if @comment.user == current_user %>
    <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
    <% end %>

    <%= link_to "Back to comments", comments_url(post_id: @comment.post_id) %>
    
    <% if @comment.user == current_user %>
    <%= button_to "Destroy this comment", @comment, method: :delete %>
    <% end %>
   
    <%= link_to "New comment", new_comment_path(post_id: @comment.post_id) %>
    <%= link_to "Back to main", root_path %>
</div>