config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :comments
  resources :posts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

    root "main#index"
    get "likes/check_like/:id", to: "likes#check_like", as: "like_post"
    get "likes/check_dislike/:id", to: "likes#check_dislike", as: "dislike_post"
    get "friends/:post_user_id", to: "friends#friendly", as: "friendly_post"
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :img_name, ImgUploader
    belongs_to :user #у одного поста один user
    has_many :comments#у одного поста много комментариев
    has_many :likes#у одного поста много лайков
    validates :description, presence: true, length: {maximum: 500 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
    before_action :authorize_user, except: [:index, :show]
    pp(11111) 
    # GET /posts or /posts.json
    def index
        pp(2222)
        @posts = Post.all
        @my_posts = Post.where(user_id: current_user.id) if current_user
    end
  
    # GET /posts/1 or /posts/1.json
    def show
        pp(333333333333333333333333)
    end
  
    # GET /posts/new
    def new
        pp(44444444444444444444444)
        @post = Post.new
    end
  
    # GET /posts/1/edit
    def edit
        pp(55555555555555555555555)
        @post = Post.find_by(user_id: current_user.id, id: (params[:id]))
        if @post.nil?
            pp(666666666666666666666666)
            redirect_to root_path
        end
    end
  
    # POST /posts or /posts.json
    def create
    pp(888888888888888888888888) 
    pp(@post) 
    pp(post_params)      
      @post = Post.new(post_params)
      @post.user_id = current_user.id
        respond_to do |format|
            if @post.save
                pp(999999999999999999999)
            format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
            format.json { render :show, status: :created, location: @post }
            else
                pp(101010101010101010)
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
        
    end
  
    
    # PATCH/PUT /posts/1 or /posts/1.json
    def update
        pp(1111111111111111111111111111)
      respond_to do |format|
        if @post.update(post_params)
            pp(121212121212121212)
          format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
          format.json { render :show, status: :ok, location: @post }
        else
            pp(1313131313131313131313)
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /posts/1 or /posts/1.json
    def destroy
        pp(14141414141414141414141)
      @post.destroy
  
      respond_to do |format|
        pp(1515151515151515151515)
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    # def authorize_user
    #     pp(1616161616161616161616)
    #     if current_user
    #         pp(17171717171717171717)
    #       return true
    #     else
    #         pp(1818181818181818)
    #       redirect_to root_path, alert: "You are not authorized to edit this post."
    #     end
    # end

    def authorize_user
        unless current_user
          redirect_to root_path, alert: "You are not authorized to edit this post."
        end
      end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        pp(191919191919191919)
        @post = Post.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        pp(20202020202020202020)
        params.require(:post).permit(:id, :img_name, :description, :user_id, :img)
      end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= form.label :img_name, style: "display: block" %>
    <%= form.file_field :img_name %>
  </div>

  

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <p>
        <strong> <%= post.user.first_name%> <%= post.user.last_name%> </strong>
    </p>
    
    <p>
        <%= image_tag post.img_name.url %>
    </p>
   
    <p>
        <strong>Description:</strong>
        <%= post.description %>
    </p>

    <!-- в таблице likes есть столбец like используется для хранения информации о дизлайках(0),лайках(1) и null(ничего не выбрано). Значение true означает, что лайк является лайком, а значение false означает, что лайк является дизлайком -->
    <p>
        <strong>Like:</strong>
        <%= post.likes.where(like: true).count %>

        <strong>Dislike:</strong>
        <%= post.likes.where(like: false).count %>
    <p>
        <strong>Comments:</strong>
        <%= post.comments.count %>
        <%= link_to 'Show comments', comments_path(post_id: post.id) %>
    </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to post", post_path(@post[:id] ) %>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <p style="color: green"><%= notice %></p>

    <h1>Posts</h1>
    <p>
    <%= link_to "All post instagram", root_path %>
    <%= link_to "New post", new_post_path %>
    </p>
    <div id="posts">
    <% @my_posts.each do |post| %>
        <%= render post %>
        <p>
        <%= link_to "Show this post", post %>
        
        </p>
    <% end %>
    </div>

<% else %>
  <h1>Home</h1>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
    <% if @post.user == current_user %>
        <%= link_to "Edit this post", edit_post_path(@post) %> 
        <%= button_to "Destroy this post", @post, method: :delete %>
    <% end %>

    <%= link_to "Back to main", root_path %>


</div>